# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconnect.proto\"O\n\x0e\x43onnectRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x19\n\x0crequest_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_request_name\"F\n\x0f\x43onnectResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x10\n\x08\x62ot_name\x18\x02 \x01(\t\x12\x0e\n\x06\x62ot_id\x18\x03 \x01(\t\"J\n\x11\x44isconnectRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\t\x12\x12\n\nleave_game\x18\x03 \x01(\x08\"8\n\x12\x44isconnectResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32x\n\rManageSession\x12.\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x12\x37\n\nDisconnect\x12\x12.DisconnectRequest\x1a\x13.DisconnectResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTREQUEST._serialized_start=17
  _CONNECTREQUEST._serialized_end=96
  _CONNECTRESPONSE._serialized_start=98
  _CONNECTRESPONSE._serialized_end=168
  _DISCONNECTREQUEST._serialized_start=170
  _DISCONNECTREQUEST._serialized_end=244
  _DISCONNECTRESPONSE._serialized_start=246
  _DISCONNECTRESPONSE._serialized_end=302
  _MANAGESESSION._serialized_start=304
  _MANAGESESSION._serialized_end=424
# @@protoc_insertion_point(module_scope)
