# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x89\x01\n\x07Message\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12&\n\x06source\x18\x02 \x01(\x0e\x32\x16.Message.MessageSource\x12\x0f\n\x07message\x18\x03 \x01(\t\"2\n\rMessageSource\x12\x08\n\x04GAME\x10\x00\x12\x0b\n\x07PRIVATE\x10\x01\x12\n\n\x06PUBLIC\x10\x02\"=\n\x18SubscribeMessagesRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\t\"J\n\x19SubscribeMessagesResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x1a\n\x08messages\x18\x02 \x03(\x0b\x32\x08.Message\"?\n\x1aUnsubscribeMessagesRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\t\"P\n\x1bUnsubscribeMessagesResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"`\n\x12SendMessageRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\t\x12\x19\n\x07message\x18\x03 \x01(\x0b\x32\x08.Message\x12\x0c\n\x04loud\x18\x04 \x01(\x08\"H\n\x13SendMessageResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=18
  _MESSAGE._serialized_end=155
  _MESSAGE_MESSAGESOURCE._serialized_start=105
  _MESSAGE_MESSAGESOURCE._serialized_end=155
  _SUBSCRIBEMESSAGESREQUEST._serialized_start=157
  _SUBSCRIBEMESSAGESREQUEST._serialized_end=218
  _SUBSCRIBEMESSAGESRESPONSE._serialized_start=220
  _SUBSCRIBEMESSAGESRESPONSE._serialized_end=294
  _UNSUBSCRIBEMESSAGESREQUEST._serialized_start=296
  _UNSUBSCRIBEMESSAGESREQUEST._serialized_end=359
  _UNSUBSCRIBEMESSAGESRESPONSE._serialized_start=361
  _UNSUBSCRIBEMESSAGESRESPONSE._serialized_end=441
  _SENDMESSAGEREQUEST._serialized_start=443
  _SENDMESSAGEREQUEST._serialized_end=539
  _SENDMESSAGERESPONSE._serialized_start=541
  _SENDMESSAGERESPONSE._serialized_end=613
# @@protoc_insertion_point(module_scope)
