# this file is automatically generated by engine/config/gen.py


import typing as T
from pydantic import Field
from engine.config import Section


class MassMurdererSection(Section):

    @staticmethod
    def sheet_range() -> T.Tuple[str, str, str]:
        return ("MassMurderer", "A1", "B15")

    @staticmethod
    def ingest(sheet_section: T.List[T.List[str]]) -> T.Dict[str, str]:
        return dict([
            (sheet_section[idx][0], sheet_section[idx][1])
            for idx in range(len(sheet_section))
        ])

    invulnerable_at_night: bool = True
    can_self_target: bool = True
    nights_between_sprees: int = 0
    immune_to_detection: bool = False
